name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: php:7.4

    steps:
    - uses: actions/checkout@v3

    - name: Execute PHP script
      run: sh -c "php build.php"
